spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_textile_industry?useUnicode=true&characterEncoding=utf-8&serverTimezone = GMT&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  #  访问静态资源css    href="/amazeframe/static/amaze/assets/..."
  #  mvc:
  #    static-path-pattern: /static/**

  # 访问静态资源css   href="/amazeframe/amaze/assets/..."
  resources:
    static-locations: classpath:/static


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.ndky.webtextile.pojo
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

#shiro:
#  login-url: /welcome
#  unauthorized-url: /unauthorized
#  anon-urls:
#    - /login
#    - /amaze/**

server:
  servlet:
    context-path: /Webtextile